### ISSUE TITLE
Too Bad

### ISSUE THREAD

**Issue by utkuseyfeli** [tuzgen/dotfiles#1]
Worst config I've seen in a while, please use your brain next time. 
Bonus Tip: fish shell is great zsh-autocomplete is shit

**Comment by utkuseyfeli** [comment]
dev didnt respond

**Comment by tuzgen** [comment]
@utkuseyfeli fish isn't posix compliant and insane one-liners sometimes simply don't work on it. Plus, I don't rely on zsh-autocomplete either, I use CTRL-R which triggers fzf on zsh_history

you are advised to **yoink** yourself off of MEMS

**Comment by utkuseyfeli** [comment]
I didn't say in anywhere to use fish as your system shell dumbo. Only unicellular beings like yourself can defend this in such manner. Regards
